import type { TriggerEvent } from "../model.ts";

export const triggerEvents: readonly TriggerEvent[] = ["ABILITY_DECLARED", "CUT_IN_USED", "DISGUISED", "CARD_DRAWN", "TURN_END", "CARD_MOVED", "CHARACTER_ENTERED", "CHARACTER_REMOVED", "ORIENTATION_CHANGED", "NEXT_HINT_TAKEN", "DEDUCTION_DECLARED", "MISLEAD_USED", "EVIDENCE_GAINED", "DEDUCTION_ENDED", "ACTION_DECLARED", "GUARD_DECLARED", "CONTACT_STARTED", "CONTACT_PRIORITY", "AP_COMPARED", "CONTACT_ENDED", "ACTION_ENDED"];
